[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dialect-mcps"
version = "0.1.0"
description = "A collection of MCP servers for Dialect Solana Blinks"
requires-python = ">=3.10"
authors = [
    {name = "Dark Research"}
]
